// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtCkj8FCOBm5rEURdT1fqIkLudX97_1cA',
    appId: '1:74739351875:android:f71510ef8d9df9abfa2ff6',
    messagingSenderId: '74739351875',
    projectId: 'todoapp-53e57',
    storageBucket: 'todoapp-53e57.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqkWVkjzE5ZamadyvpH2GjZN9-KyHxXcE',
    appId: '1:74739351875:web:6291b514eaf12398fa2ff6',
    messagingSenderId: '74739351875',
    projectId: 'todoapp-53e57',
    authDomain: 'todoapp-53e57.firebaseapp.com',
    storageBucket: 'todoapp-53e57.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkiMrumvVBgZSp3EZ4n7MWfiLbTPFEUms',
    appId: '1:74739351875:ios:835699d90a4c5a88fa2ff6',
    messagingSenderId: '74739351875',
    projectId: 'todoapp-53e57',
    storageBucket: 'todoapp-53e57.firebasestorage.app',
    iosBundleId: 'com.example.fireTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqkWVkjzE5ZamadyvpH2GjZN9-KyHxXcE',
    appId: '1:74739351875:web:bf5a76ac73fc957afa2ff6',
    messagingSenderId: '74739351875',
    projectId: 'todoapp-53e57',
    authDomain: 'todoapp-53e57.firebaseapp.com',
    storageBucket: 'todoapp-53e57.firebasestorage.app',
  );

}